### ISSUE TITLE
Get a custom domain name

### ISSUE THREAD

**Issue by leewujung** [BOAT-ocean-acoustics/boat-ocean-acoustics.github.io#1]
Right now the website RUL is https://boat-ocean-acoustics.github.io/boat-2024/
Would be better to have something like https://boat-2024.github.io as the domain name.

**Comment by valentina-s** [comment]
If we rename the repo `boat-website` to `boat-ocean-acoustics.github.io` we should be able to serve from

`boat-ocean-acoustics.github.io`

Do we want something else?

**Comment by leewujung** [comment]
Yes, done!
