### ISSUE TITLE
Make a video for beampattern widget

### ISSUE THREAD

**Issue by leewujung** [BOAT-ocean-acoustics/boat-ocean-acoustics.github.io#18]

**Comment by valentina-s** [comment]
@leewujung @bthefner Below is an example with video. What should I put for a title of the plot? I put Far Field Intensity based on the function.
https://www.loom.com/share/6a08e8d72fc943e091eb26c6e5a8f458?sid=7005d796-9113-4e43-b027-a560eafffc65

**Comment by bthefner** [comment]
I like the video. How about, "Far field beam pattern?"

**Comment by valentina-s** [comment]
#49 addresses this issue
